/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Clases.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jared
 */
public class alumnosSinPagar extends javax.swing.JFrame {
DefaultTableModel srt;
    /**
     * Creates new form alumnosSinPagar
     */
    Alumnos alumnos;
  

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(HIDE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }
    //El metodo constructor va a obtener como parametro un objeto de tipo Alumnos que es el que en el formulario main mandamos cuando instanciamos un formulario de esta clase , ahi contendra todos los alumnos
    public alumnosSinPagar(Alumnos alumnos) {
        initComponents();
        this.alumnos = alumnos;
        srt = new DefaultTableModel();
        srt.addColumn("Codigo");
        srt.addColumn("Nombre");
        srt.addColumn("Edad");
        srt.addColumn("Cat_Codigo");
        srt.addColumn("Cat_Descripcion");
        srt.addColumn("Esc_Codigo");
        srt.addColumn("Esc_Descripcion");
        srt.addColumn("Pago_Inscripcion");
        this.table.setModel(srt);
        //Hago un bucle foreach para saber que alumnos han pagado o no 
        for(Alumno alumno: this.alumnos.getAllAlumnnos()){
            //Si el alumno no ha pagado pues agrego los campos a un vector de tipo string y al final lo meto a la tabla
            if(alumno.getPago()==false){
                System.out.println(alumno.getNombre());
                String data[] = new String[8];
                data[0] = alumno.getCodigo();
                data[1] = alumno.getNombre();
                data[2] = String.valueOf(alumno.getEdad());
                data[3] = alumno.getOcategoria().getCodigo();
                data[4] = alumno.getOcategoria().getDescripcion();
                data[5] = alumno.getOescuela().getCodigo();
                data[6] = alumno.getOescuela().getDescription();
                data[7] = (alumno.getPago())?"Si":"No";
                srt.addRow(data);
            }
            
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alumnos sin pagar");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alumnosSinPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alumnosSinPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alumnosSinPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alumnosSinPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
